const data = [
    {
      name: "Fast x",
      duration: "2 hr 30 min",
      date: "02/01/2023",
      rating: "4.3",
      img: "https://www.thefilmik.com/wp-content/uploads/2023/04/Fast-X.webp",
    },
    {
      name: "Extraction 2",
      duration: "2 hr 30 min",
      date: "02/02/2023",
      rating: "4.3",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIYJju9y1y-O7Y1KXu7y1baVietxs0rahfXjBV7AcOYrQysb7oFLYAccbEQ_fn9o4BJIk&usqp=CAU",
    },
    {
      name: "John Wick 4",
      duration: "2 hr 30 min",
      date: "02/03/2023",
      rating: "4.3",
      img: "https://m.media-amazon.com/images/I/81fk-N7tvbL._AC_UF1000,1000_QL80_.jpg",
    },
    {
      name: "Spider-Man:Acroos the spider verse",
      duration: "2 hr 30 min",
      date: "04/04/2023",
      rating: "4.3",
      img: "https://play-lh.googleusercontent.com/tRZYfjWo9wpy_yTCjEaIAikiJZzHYNDZN_6teeZ1JM9MEanq4PLvEmSGtn2AtTLO1XY-cA",
    },{
      name: "Mission Impossible",
      duration: "2 hr 30 min",
      date: "02/05/2023",
      rating: "4.3",
      img: "https://m.media-amazon.com/images/M/MV5BYzFiZjc1YzctMDY3Zi00NGE5LTlmNWEtN2Q3OWFjYjY1NGM2XkEyXkFqcGdeQXVyMTUyMTUzNjQ0._V1_FMjpg_UX1000_.jpg",
    },
    {
      name: "Transformer",
      duration: "2 hr 30 min",
      date: "02/06/2023",
      rating: "4.3",
      img: "https://upload.wikimedia.org/wikipedia/en/1/1c/Transformers-_Rise_of_the_Beasts.jpg",
    },{
      name: "Barbie",
      duration: "2 hr 30 min",
      date: "02/07/2023",
      rating: "4.3",
      img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Barbie_2023_poster.jpg",
    },
    {
      name: "Openheimer",
      duration: "2 hr 30 min",
      date: "02/08/2023",
      rating: "4.3",
      img: "https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_.jpg",
    },
    {
      name: "The Flash",
      duration: "2 hr 30 min",
      date: "02/09/2023",
      rating: "4.3",
      img: "https://m.media-amazon.com/images/M/MV5BMTkyMmMxMzYtMzU4Zi00YjY3LWJmODEtMWZkYTMwZWE4ZGI3XkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg",
    },
    {
      name: "Gurdians Of The Galaxy",
      duration: "2 hr 30 min",
      date: "04/10/2023",
      rating: "4.3",
      img: "https://upload.wikimedia.org/wikipedia/en/7/74/Guardians_of_the_Galaxy_Vol._3_poster.jpg",
    },{
      name: "Ant Man",
      duration: "2 hr 30 min",
      date: "02/12/2023",
      rating: "4.3",
      img: "https://lumiere-a.akamaihd.net/v1/images/pp_disneymovies_antmanquantumania_1721_94516e7a.jpeg",
    },
    {
      name: "Blue Beettle",
      duration: "2 hr 30 min",
      date: "02/11/2023",
      rating: "4.3",
      img: "https://m.media-amazon.com/images/M/MV5BODkyZjcyOGMtZWVhYy00ZWEyLWJlZDItZDA2OTBhNGZmMjBiXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg",
    },{
      name: "Evil Dead Rise",
      duration: "2 hr 30 min",
      date: "02/04/2023",
      rating: "4.3",
      img: "https://m.media-amazon.com/images/M/MV5BMmZiN2VmMjktZDE5OC00ZWRmLWFlMmEtYWViMTY4NjM3ZmNkXkEyXkFqcGdeQXVyMTI2MTc2ODM3._V1_FMjpg_UX1000_.jpg",
    },
    {
      name: "Pushpa",
      duration: "2 hr 30 min",
      date: "02/05/2023",
      rating: "4.3",
      img: "https://m.media-amazon.com/images/M/MV5BNGZlNTFlOWMtMzUwNC00ZDdhLTk0MWUtOGZjYzFlOTBmNDdhXkEyXkFqcGdeQXVyMTUyNjIwMDEw._V1_.jpg",
    },
    {
      name: "Jailer",
      duration: "2 hr 30 min",
      date: "02/07/2023",
      rating: "4.3",
      img: "https://upload.wikimedia.org/wikipedia/en/c/cb/Jailer_2023_Tamil_film_poster.jpg",
    },
    {
      name: "Temper",
      duration: "2 hr 30 min",
      date: "04/09/2023",
      rating: "4.3",
      img: "https://images.jdmagicbox.com/comp/jd_social/news/2018aug06/image-197597-l86guhdvk9.jpg",
    },{
      name: "RRR",
      duration: "2 hr 30 min",
      date: "02/02/2023",
      rating: "4.3",
      img: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/RRR_Poster.jpg/220px-RRR_Poster.jpg",
    },
    {
      name: "Baby",
      duration: "2 hr 30 min",
      date: "02/05/2023",
      rating: "4.3",
      img: "https://upload.wikimedia.org/wikipedia/en/4/46/Baby_theatrical_poster.jpg",
    }
  ];
  export default data